/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.clanarine;

import domen.Clan;
import domen.Clanarina;
import domen.StavkaClanarine;
import domen.Zaposleni;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import poslovnaLogika.Kontroler;

/**
 *
 * @author mdzeletovic
 */
public class FrmUnosClanarine extends javax.swing.JFrame {

    /**
     * Creates new form FrmUnosClanarine
     */
    public FrmUnosClanarine() throws Exception {
        initComponents();
        srediFormu();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jBtnZapamti = new javax.swing.JButton();
        jTxtVaziOd = new javax.swing.JTextField();
        jTxtVaziDo = new javax.swing.JTextField();
        jTxtCena = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableStavke = new javax.swing.JTable();
        jBtbDodajRed = new javax.swing.JButton();
        jBtnObrisiRed = new javax.swing.JButton();
        jCmbZaposleni = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocationByPlatform(true);

        jLabel1.setText("ZaposleniID");
        jLabel1.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel2.setText("VaziOd");
        jLabel2.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel3.setText("VaziDo");
        jLabel3.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel4.setText("Cena");
        jLabel4.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(47, 14));

        jBtnZapamti.setText("Zapamti");
        jBtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZapamtiActionPerformed(evt);
            }
        });

        jTableStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Naziv", "Broj termina nedeljno", "Cena termina"
            }
        ));
        jScrollPane2.setViewportView(jTableStavke);

        jBtbDodajRed.setText("Dodaj red");
        jBtbDodajRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtbDodajRedActionPerformed(evt);
            }
        });

        jBtnObrisiRed.setText("Obrisi red");
        jBtnObrisiRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiRedActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxtCena, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jTxtVaziDo, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jTxtVaziOd, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jCmbZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(91, 91, 91))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtbDodajRed)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnObrisiRed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnZapamti))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVaziOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVaziDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtCena, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnZapamti)
                    .addComponent(jBtbDodajRed)
                    .addComponent(jBtnObrisiRed))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZapamtiActionPerformed
        try {
            SimpleDateFormat df = new SimpleDateFormat("yyyy-MM-dd");
            Date vaziOd = df.parse(jTxtVaziOd.getText().trim());
            Date vaziDo = df.parse(jTxtVaziDo.getText().trim());
            Double cena = Double.parseDouble(jTxtCena.getText());
            Zaposleni zaposleni = (Zaposleni) jCmbZaposleni.getSelectedItem();
            Clanarina cl = new Clanarina(vaziOd, vaziDo, cena, zaposleni);
            cl.setStavke(((StavkaTableModel) jTableStavke.getModel()).vratiStavke());

            Kontroler.getInstance().dodajClanarinu(cl);
            JOptionPane.showMessageDialog(this, "Nova clanarina je sacuvana!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_jBtnZapamtiActionPerformed

    private void jBtbDodajRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtbDodajRedActionPerformed
        ((StavkaTableModel) jTableStavke.getModel()).dodajRed();
    }//GEN-LAST:event_jBtbDodajRedActionPerformed

    private void jBtnObrisiRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiRedActionPerformed
        int red = jTableStavke.getSelectedRow();
        if (red < 0) {
            JOptionPane.showMessageDialog(this, "red!");
        } else {
            ((StavkaTableModel) jTableStavke.getModel()).obrisiRed(red);
        }
    }//GEN-LAST:event_jBtnObrisiRedActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtbDodajRed;
    private javax.swing.JButton jBtnObrisiRed;
    private javax.swing.JButton jBtnZapamti;
    private javax.swing.JComboBox<String> jCmbZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableStavke;
    private javax.swing.JTextField jTxtCena;
    private javax.swing.JTextField jTxtVaziDo;
    private javax.swing.JTextField jTxtVaziOd;
    // End of variables declaration//GEN-END:variables

    private void srediFormu() throws Exception {

        jTableStavke.setModel(new StavkaTableModel());
        
        List<Zaposleni> lista = Kontroler.getInstance().vratiZaposlene();
        if (lista.size()>0) {
            Collections.sort(lista, new Comparator<Zaposleni>() {
                @Override
                public int compare(Zaposleni o1, Zaposleni o2) {
                    return o1.toString().compareTo(o2.toString());
                }
            });
        }
        jCmbZaposleni.setModel(new DefaultComboBoxModel(lista.toArray()));
    }
}
