/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.clanovi;

import domen.Clan;
import domen.Lice;
import java.awt.BorderLayout;
import java.awt.Component;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import poslovnaLogika.Kontroler;

/**
 *
 * @author mdzeletovic
 */
public class FrmClanovi extends javax.swing.JFrame {

    /**
     * Creates new form FrmClanovi
     */
    
    int modRadaForme = 0;  // 1 - unios, 2 - izmena, 3 - pregled
    public FrmClanovi(int modRada) {
        initComponents();
        this.modRadaForme = modRada;
        jTxtLiceID.setEnabled(false);  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTxtLiceID = new javax.swing.JTextField();
        jTxtJmbg = new javax.swing.JTextField();
        jTxtIme = new javax.swing.JTextField();
        jTxtPrezime = new javax.swing.JTextField();
        jTxtAdresa = new javax.swing.JTextField();
        jTxtEmail = new javax.swing.JTextField();
        jTxtTelefon = new javax.swing.JTextField();
        jTxtPoslednjaUplata = new javax.swing.JTextField();
        jBtnZapamti = new javax.swing.JButton();
        jBtnTrazi = new javax.swing.JButton();
        jBtnPrikaziSveClanove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos clana");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jLabel1.setText("LiceID");
        jLabel1.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel2.setText("JMBG");
        jLabel2.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel3.setText("Ime");
        jLabel3.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel4.setText("Prezime");
        jLabel4.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel5.setText("Adresa");
        jLabel5.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel6.setText("e-mail");
        jLabel6.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel7.setText("Telefon");
        jLabel7.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel7.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel7.setPreferredSize(new java.awt.Dimension(47, 14));

        jLabel8.setText("Poslednja uplata");
        jLabel8.setMaximumSize(new java.awt.Dimension(47, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(47, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(47, 14));

        jTxtLiceID.setName("LiceID"); // NOI18N

        jTxtJmbg.setName("JMBG"); // NOI18N

        jTxtIme.setName("Adresa"); // NOI18N

        jTxtPrezime.setName("Ime"); // NOI18N

        jTxtAdresa.setName("Prezime"); // NOI18N

        jTxtEmail.setName("Email"); // NOI18N

        jTxtTelefon.setName("Telefon"); // NOI18N

        jTxtPoslednjaUplata.setName("PoslednjaUplata"); // NOI18N

        jBtnZapamti.setText("Zapamti");
        jBtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZapamtiActionPerformed(evt);
            }
        });

        jBtnTrazi.setText("Trazi");
        jBtnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTraziActionPerformed(evt);
            }
        });

        jBtnPrikaziSveClanove.setText("Prikazi sve clanove");
        jBtnPrikaziSveClanove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPrikaziSveClanoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnZapamti))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtPoslednjaUplata, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLiceID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnTrazi)
                        .addGap(61, 61, 61)
                        .addComponent(jBtnPrikaziSveClanove)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtLiceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtJmbg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtAdresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPoslednjaUplata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnTrazi)
                    .addComponent(jBtnZapamti)
                    .addComponent(jBtnPrikaziSveClanove))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZapamtiActionPerformed

        try {
            //DateFormat df = new SimpleDateFormat("dd.MM.yyyy");
            Long liceID = null;
            String jmbg = jTxtJmbg.getText().trim();
            String ime = jTxtIme.getText().trim();
            String prezime = jTxtPrezime.getText().trim();
            String adresa = (jTxtAdresa.getText() != null) ?  jTxtAdresa.getText().trim() :  null;
            String email = (jTxtEmail.getText() != null) ?  jTxtEmail.getText().trim() :  null;
            String tel = jTxtTelefon.getText().trim();
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            java.util.Date datum1 = sdf.parse(jTxtPoslednjaUplata.getText().trim());
            Clan clan = new Clan(liceID,datum1,jmbg, ime, prezime, adresa, email, tel);   
            Kontroler.getInstance().dodajClana(clan);
            
            
            JOptionPane.showMessageDialog(this, "Novi CLAN je sacuvan!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jBtnZapamtiActionPerformed

    private void jBtnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTraziActionPerformed
        
        try {
            String whereUslov = "";
            List<Component> listaKomponenti = Arrays.asList(getContentPane().getComponents());
            List<Component> lsta2 = listaKomponenti.stream().filter(x -> x instanceof JTextField).collect(Collectors.toList());
            lsta2.stream().filter((c) -> (!(((JTextField)c).getText().equals(""))
                    && !(((JTextField)c).getText().isEmpty()))).forEach((c) -> {
                String vrednost = ((JTextField) c).getText();
                String nazivAtr = ((JTextField) c).getName();
                whereUslov.concat(" " + nazivAtr + " = " + "'" + vrednost + "' AND " );
            });
            Kontroler.getInstance().traziClana(whereUslov);
        } catch (Exception ex) {
            Logger.getLogger(FrmClanovi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnTraziActionPerformed

    private void jBtnPrikaziSveClanoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPrikaziSveClanoveActionPerformed

            FrmPrikazClanova f = new FrmPrikazClanova();
            JDialog dialog = new JDialog(this, "Prikaz clanova", true);
            dialog.setLayout(new BorderLayout());
            dialog.add(f, BorderLayout.CENTER);
            dialog.pack();
            dialog.setVisible(true);

    }//GEN-LAST:event_jBtnPrikaziSveClanoveActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnPrikaziSveClanove;
    private javax.swing.JButton jBtnTrazi;
    private javax.swing.JButton jBtnZapamti;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTxtAdresa;
    private javax.swing.JTextField jTxtEmail;
    private javax.swing.JTextField jTxtIme;
    private javax.swing.JTextField jTxtJmbg;
    private javax.swing.JTextField jTxtLiceID;
    private javax.swing.JTextField jTxtPoslednjaUplata;
    private javax.swing.JTextField jTxtPrezime;
    private javax.swing.JTextField jTxtTelefon;
    // End of variables declaration//GEN-END:variables
}
