/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.clanovi;

import domen.Clan;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import poslovnaLogika.Kontroler;

/**
 *
 * @author mdzeletovic
 */
public class JDPrikazClanova extends javax.swing.JDialog {

    List<Clan> listaZaPrikaz;
    Clan clanSel;

    /**
     * Creates new form JDPrikazClanova
     */
    public JDPrikazClanova(java.awt.Frame parent, boolean modal, List<Clan> listaZaPrikaz) {
        super(parent, modal);
        this.listaZaPrikaz = listaZaPrikaz;
        initComponents();
        srediFormu();
        jTblClanovi.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent event) {
                if (jTblClanovi.getSelectedRowCount() == 1) {
                    jBtnIzmeni.setEnabled(true);
                    jBtnObrisiClana.setEnabled(true);
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCmbFilter = new javax.swing.JComboBox<>();
        jTxtFilter = new javax.swing.JTextField();
        jBtnTrazi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jBtnIzmeni = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblClanovi = new javax.swing.JTable();
        jBtnObrisiClana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnTrazi.setText("Trazi");
        jBtnTrazi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnTraziActionPerformed(evt);
            }
        });

        jLabel1.setText("Filter po:");

        jBtnIzmeni.setText("Izmeni clana");
        jBtnIzmeni.setEnabled(false);
        jBtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIzmeniActionPerformed(evt);
            }
        });

        jTblClanovi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "LiceID", "JMBG", "Ime", "Prezime", "Adresa", "Email", "Telefon", "PoslednjaUplata"
            }
        ));
        jTblClanovi.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jTblClanovi);

        jBtnObrisiClana.setText("Obrisi clana");
        jBtnObrisiClana.setEnabled(false);
        jBtnObrisiClana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnObrisiClanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(jBtnIzmeni)
                .addGap(104, 104, 104)
                .addComponent(jBtnObrisiClana)
                .addGap(146, 146, 146))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 63, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(110, 110, 110)
                            .addComponent(jCmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jTxtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jBtnTrazi))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(8, 8, 8)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 63, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnObrisiClana)
                    .addComponent(jBtnIzmeni))
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 53, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jCmbFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addComponent(jTxtFilter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jBtnTrazi))
                    .addGap(11, 11, 11)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 87, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnTraziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnTraziActionPerformed
        RowFilter rf = RowFilter.regexFilter(jTxtFilter.getText(), jCmbFilter.getSelectedIndex());
        final TableRowSorter<TableModel> sorter = new TableRowSorter<TableModel>(jTblClanovi.getModel());
        jTblClanovi.setRowSorter(sorter);
        sorter.setRowFilter(rf);
    }//GEN-LAST:event_jBtnTraziActionPerformed

    private void jBtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIzmeniActionPerformed
        int pom = jTblClanovi.getSelectedRow();
        long LiceID = (long) jTblClanovi.getModel().getValueAt(pom, 0);
        Clan selektovaniClan = ((ClanTableModel) jTblClanovi.getModel()).getClanPoId(LiceID);

        FrmClanoviUnosPretraga frm = new FrmClanoviUnosPretraga(3, selektovaniClan);
        frm.setVisible(true);
        JOptionPane.showMessageDialog(this, "Sistem je pronašao podatke o izabranom članu");

        this.dispose();

    }//GEN-LAST:event_jBtnIzmeniActionPerformed

    private void jBtnObrisiClanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnObrisiClanaActionPerformed
        try {
            int pom = jTblClanovi.getSelectedRow();
            long LiceID = (long) jTblClanovi.getModel().getValueAt(pom, 0);
            //Clan selektovaniClan = ((ClanTableModel) jTblClanovi.getModel()).getClanPoId(LiceID);

            Kontroler.getInstance().brisiClana(LiceID);

            JOptionPane.showMessageDialog(this, "obrisan clan");

            this.dispose();
        } catch (Exception ex) {
            Logger.getLogger(JDPrikazClanova.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jBtnObrisiClanaActionPerformed

    private void srediFormu() {

        try {
            for (int i = 0; i < jTblClanovi.getColumnCount(); i++) {
                jCmbFilter.addItem(jTblClanovi.getColumnName(i));
            }

            ClanTableModel model = new ClanTableModel(listaZaPrikaz, jTblClanovi);

            jTblClanovi.setModel(model);

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIzmeni;
    private javax.swing.JButton jBtnObrisiClana;
    private javax.swing.JButton jBtnTrazi;
    private javax.swing.JComboBox<String> jCmbFilter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTblClanovi;
    private javax.swing.JTextField jTxtFilter;
    // End of variables declaration//GEN-END:variables
}
