/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.racuni;

import forme.clanovi.*;
import domen.Clan;
import domen.Clanarina;
import domen.Lice;
import domen.Racun;
import domen.Zaposleni;
import java.awt.BorderLayout;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.sql.Date;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Collectors;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import poslovnaLogika.Kontroler;

/**
 *
 * @author mdzeletovic
 */
public class UnosRacunaa extends javax.swing.JFrame {

    /**
     * Creates new form UnosRacunaa
     */
   // int modRadaForme = 0;  // 1 - unios, 2 - izmena, 3 - pregled

    public UnosRacunaa() throws Exception {
        initComponents();
        srediFormu();


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnZapamti = new javax.swing.JButton();
        jCmbClan = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jCmbClanarina = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jCmbZaposleni = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Unos clana");
        setLocation(new java.awt.Point(0, 0));
        setLocationByPlatform(true);

        jBtnZapamti.setText("Zapamti");
        jBtnZapamti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnZapamtiActionPerformed(evt);
            }
        });

        jLabel9.setText("Clan:");

        jLabel10.setText("Clanarina:");

        jLabel11.setText("Zaposleni:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnZapamti)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jCmbClan, 0, 152, Short.MAX_VALUE)
                        .addComponent(jCmbClanarina, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCmbZaposleni, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbClan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbClanarina, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmbZaposleni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(46, 46, 46)
                .addComponent(jBtnZapamti)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnZapamtiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnZapamtiActionPerformed

        try {
            
            Zaposleni zaposleni = (Zaposleni) jCmbZaposleni.getSelectedItem();
            Clanarina clanarina = (Clanarina) jCmbClanarina.getSelectedItem();
            Clan clan = (Clan) jCmbClan.getSelectedItem();
            java.util.Date datumIzdavanja = new Date(new java.util.Date().getTime());
            Double cena = clanarina.getCena();
            
            Racun r = new Racun(datumIzdavanja, cena, zaposleni, clan, clanarina);
            Kontroler.getInstance().dodajRacun(r);

            JOptionPane.showMessageDialog(this, "Uspešno kreiran novi račun!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }//GEN-LAST:event_jBtnZapamtiActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnZapamti;
    private javax.swing.JComboBox<String> jCmbClan;
    private javax.swing.JComboBox<String> jCmbClanarina;
    private javax.swing.JComboBox<String> jCmbZaposleni;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables





    private void srediFormu() throws Exception {
        List<Clan> lista = Kontroler.getInstance().vratiClanove();
        if (lista.size()>0) {
            Collections.sort(lista, new Comparator<Clan>() {
                @Override
                public int compare(Clan o1, Clan o2) {
                    return o1.toString().compareTo(o2.toString());
                }
            });
        }
        jCmbClan.setModel(new DefaultComboBoxModel(lista.toArray()));
        
        List<Clanarina> lista2 = Kontroler.getInstance().vratiClanarine();
        if (lista.size()>0) {
            Collections.sort(lista2, new Comparator<Clanarina>() {
                @Override
                public int compare(Clanarina o1, Clanarina o2) {
                    return  o1.getClanarinaID() > o2.getClanarinaID() ? +1 : o1.getClanarinaID() < o2.getClanarinaID() ? -1 : 0;    
                }
            });
        }
        jCmbClanarina.setModel(new DefaultComboBoxModel(lista2.toArray()));
        
        List<Zaposleni> lista3 = Kontroler.getInstance().vratiZaposlene();
        if (lista.size()>0) {
            Collections.sort(lista3, new Comparator<Zaposleni>() {
                @Override
                public int compare(Zaposleni o1, Zaposleni o2) {
                    return o1.toString().compareTo(o2.toString());
                }
            });
        }
        jCmbZaposleni.setModel(new DefaultComboBoxModel(lista3.toArray()));
    }
}
